volumes:
  mysql-data:
    name: AppMultiproposito-data

networks:
  AppMultiproposito-data:
    name: AppMultiproposito-network

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: AppMultiproposito-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      - AppMultiproposito-data

  php:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: AppMultiproposito-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - AppMultiproposito-data
